### ISSUE TITLE
send mail to iit teachers 

### ISSUE THREAD

**Issue by ankushjamdagani** [software-engineering-for-life/journey-to-be-a-better-software-engineer#2]
** Introduction - About Education and all **
** Researched about the teacher ver the internet*
  > And felt that interests match with the same domain. Hence, you would be a great asset to me in my learning of this particular project.

**Comment by rashmisangwan** [comment]
# Artificial INtelligence - 
--------------

  * Machine Learning
  * Pattern Recognition
  * Image Processing
  * Algorithm
  * Neural Science
  * Game Theory
  * Pattern Recognition
  * NLP
  * Software Engineering
  * spatial data structures
  * Formal methods, programming languages, software engineering 
  * Scientific visualization
